---
# defaults file for wadsworth
install_path: /srv/wadsworth
jira_creds_source_file: /srv/wadsworth/jira-creds
repo_url: https://github.com/eriknelson/wadsworth
version: v0.1.0
systemd_custom_install_path: /etc/systemd/system
nodejs_version: "14.15.0"
nodejs_download_file: "node-v{{ nodejs_version }}-linux-x64.tar.xz"
nodejs_download_dir: "/tmp"
nodejs_fq_download_path: "{{ nodejs_download_dir }}/{{ nodejs_download_file }}"
nodejs_download_url: "https://nodejs.org/dist/v14.15.0/{{ nodejs_download_file }}"
nodejs_install_root: /opt/nodejs
start_script: "{{ install_path }}/wadsworth.sh"
install_nodejs_tarball: true